### PR TITLE
Harshit

### PR DESCRIPTION
**Pull request by harshitsinghvi22**

### CODE REVIEW

**Review by ojhughes — COMMENTED** [review]
This looks really cool, but doesn't `helm publish` already do this for us? Could we just commit / push index.yaml after the publish by using a docker volume

**Comment by harshitsinghvi22** [comment]
> This looks really cool, but doesn't `helm publish` already do this for us? Could we just commit / push index.yaml after the publish by using a docker volume

I cannot find anything like `helm publish` under helm list of commands

**Comment by ojhughes** [comment]
sorry I mean helm package

**Comment by harshitsinghvi22** [comment]
> sorry I mean helm package

helm package does not update the index.yaml...we need to manually update the index.yaml , helm package just gives you a .tgz and we push it to the helm repo using one of our scripts

**Comment by ojhughes** [comment]
I mean this https://helm.sh/docs/helm/helm_repo_index/

**Comment by harshitsinghvi22** [comment]
> I mean this https://helm.sh/docs/helm/helm_repo_index/

not aware of this ..will check

**Pull request closed without merging**
