### PR TITLE
Prevent duplicate entries in ConfigMap

### LINKED ISSUE #119: [Bug]: Duplicate key in default-config data.
### What happened?

Some keys like 
- server.directories.import
- server.jvm.additional
are duplicated across the data section of the default config map, causing errors in config map creation and/or helm rendering the templates.

### Chart Name

neo4j

### Chart Version

5.2.0

### Environment

Issue seen on all the cloud providers (GCP , AWS , AKS)

### Relevant log output

```shell
# values.yaml
neo4j:
  name: neo-name
  password: ""
volumes:
  data:
    mode: "defaultStorageClass"
services:
  neo4j:
    enabled: false
jvm:
  useNeo4jDefaultJvmArguments: true

# in the output of: 
# helm template -n my-namespace -f values.yaml my-graph neo4j/neo4j

# Source: neo4j/templates/neo4j-config.yaml
# Default Neo4j config values, these are overridden by user-provided values in my-graph-user-config
apiVersion: v1
kind: ConfigMap
metadata:
  name: "my-graph-default-config"
  namespace: "my-namespace"
  labels:
    app: "neo-name"    
data:

  # Neo4j defaults
  server.directories.import: import
  server.bolt.enabled: 'true'
  server.http.enabled: 'true'
  server.https.enabled: 'false'
  db.tx_log.rotation.retention_policy: 1 days
  server.jvm.additional: -XX:+UseG1GC
  server.jvm.additional: -XX:-OmitStackTraceInFastThrow
  server.jvm.additional: -XX:+AlwaysPreTouch
  server.jvm.additional: -XX:+UnlockExperimentalVMOptions
  server.jvm.additional: -XX:+TrustFinalNonStaticFields
  server.jvm.additional: -XX:+DisableExplicitGC
  server.jvm.additional: -Djdk.nio.maxCachedBufferSize=1024
  server.jvm.additional: -Dio.netty.tryReflectionSetAccessible=true
  server.jvm.additional: -Djdk.tls.ephemeralDHKeySize=2048
  server.jvm.additional: -Djdk.tls.rejectClientInitiatedRenegotiation=true
  server.jvm.additional: -XX:FlightRecorderOptions=stackdepth=256
  server.jvm.additional: -XX:+UnlockDiagnosticVMOptions
  server.jvm.additional: -XX:+DebugNonSafepoints
  server.jvm.additional: --add-opens=java.base/java.nio=ALL-UNNAMED
  server.jvm.additional: --add-opens=java.base/java.io=ALL-UNNAMED
  server.jvm.additional: --add-opens=java.base/sun.nio.ch=ALL-UNNAMED
  server.jvm.additional: -Dlog4j2.disable.jmx=true
  server.windows_service_name: neo4j
  server.panic.shutdown_on_panic: 'true'
  
  server.logs.config: /config/server-logs.xml/server-logs.xml
  server.logs.user.config: /config/user-logs.xml/user-logs.xml

  # Helm defaults

  # Bolt keep alive
  # this helps to ensure that LoadBalancers do not close bolt connections that are in use but appear idle
  server.bolt.connection_keep_alive: "30s"
  server.bolt.connection_keep_alive_for_requests: "ALL"
  server.bolt.connection_keep_alive_streaming_scheduling_interval: "30s"

  # If we set default advertised address it over-rides the bolt address used to populate the browser in a really annoying way
  # dbms.default_advertised_address: "$(bash -c 'echo ${SERVICE_DOMAIN}')"


  # Other
  internal.dbms.ssl.system.ignore_dot_files: "true"
  # Logging
  server.directories.logs: "/logs"
  # Import
  server.directories.import: "/import"

  # Use more reliable defaults SSL / TLS settings for K8s
  dbms.ssl.policy.bolt.client_auth: "NONE"
  dbms.ssl.policy.https.client_auth: "NONE"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rlch**
- Allow Values.volumes.import to propagate server.directories.import
- Fix unmigrated `dbms.jvm.additional` regex

Fixes #119

### CODE REVIEW

**Comment by rlch** [comment]
I assume I should merge this into `5.2`? Should I change the target?

**Comment by rlch** [comment]
^ Also noticed that the apoc ConfigMap doesn't use the fully qualified name if provided

**Comment by ojhughes** [comment]
Thanks for the contribution @rlch, dev is the correct target. Would you mind adding a unit test case for this?

**Comment by rlch** [comment]
Hey @ojhughes, could you clarify what test-cases you'd like to see, and is there any documentation around your unit-testing practices?

As per the migration guide for v5:
https://neo4j.com/docs/upgrade-migration-guide/current/version-5/changelogs/configuration-settings/
this PR is just dealing with an unmigrated `dbms.jvm.additional` key, as well as ensuring the APOC ConfigMap name matches that of the volume template.

**Comment by ojhughes** [comment]
@rlch Sorry for the delay I missed your comment. no docs really, I think we just need to add a test case here https://github.com/neo4j/helm-charts/blob/dev/internal/unit_tests/neo4j_configuration_test.go

**Comment by harshitsinghvi22** [comment]
this is fixed with this
https://github.com/neo4j/helm-charts/commit/c59a10b317d06304ae19b149f6d662618bd95444

**Pull request closed without merging**
