### PR TITLE
Adds support for priority classes (4.4)

### PR DESCRIPTION
**Pull request by SansGuidon**
- Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

### CODE REVIEW

**Comment by SansGuidon** [comment]
Hi @harshitsinghvi22 , is it possible to get news about the support of priority classes for this release as this PR gets closed ?

**Comment by harshitsinghvi22** [comment]
Hi @MorganGeek ,

Apologies for accidentally closing your pull request.

The initial repo has been getting synced from our private repo and now we have made a decision to make the repo public completely and have stopped the sync job.

This required us to do a clean slate of the git repo and mirror it from our private repo. While doing the same your pull request got closed.

I have reopened it however it would be great if you can create a feature request under Github issues.

I know how it feels when the pull request gets closed without any explanation.
Once again , Apologies for the inconvenience caused. 

Appreciate your time and effort in creating this PR.

Thanks,
Harshit

**Comment by SansGuidon** [comment]
Thank you for your feedback, @harshitsinghvi22 , it's much appreciated :-) 
I'll add a feature request then :-) , should I then submit my PR linked to this feature request or just wait ?

**Comment by harshitsinghvi22** [comment]
@MorganGeek just a feature request will be helpful

**Comment by SansGuidon** [comment]
Thank you @harshitsinghvi22 : https://github.com/neo4j/helm-charts/issues/15

**Pull request closed without merging**
